CREATE TABLE USERS
(
    ID               BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    USERNAME         VARCHAR(45) NOT NULL UNIQUE,
    PASSWORD         VARCHAR(90) NOT NULL,
    IS_ACTIVE        BIT,
    ROLES            VARCHAR(31),
    GREEN_BAY_DOLLAR INT
);

CREATE TABLE ITEMS
(
    ID             BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NAME           VARCHAR(31),
    DESCRIPTION    VARCHAR(31),
    URL            VARCHAR(31),
    STARTING_PRICE INT,
    PURCHASE_PRICE INT,
    IS_SOLD        BIT,
    USER_ID        BIGINT
);

CREATE TABLE BIDS
(
    ID      BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    PRICE   INT,
    ITEM_ID BIGINT,
    USER_ID BIGINT
);

ALTER TABLE ITEMS
    ADD FOREIGN KEY (USER_ID) REFERENCES USERS (ID);
ALTER TABLE BIDS
    ADD FOREIGN KEY (USER_ID) REFERENCES USERS (ID);
ALTER TABLE BIDS
    ADD FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ID);